### ISSUE TITLE
refactor: lasr_object_recognition_yolo provides functionality with no replacement

### ISSUE THREAD

**Issue by insertish** [LASR-at-Home/Base#93]
`detect_objects_v8.py` is currently used throughout the project with no replacement

https://github.com/LASR-at-Home/Base/blob/e2ded26f89fb7cee4e4b796b497aeecc261b1d9d/legacy/lasr_object_detection_yolo/src/lasr_object_detection_yolo/detect_objects_v8.py

This seems to be mostly code that should be in the packages that actually consume yolov8?

**Comment by jws-1** [comment]
Closed by #129.
